/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface BookingInput {
    customerName: string;
    serviceType: ServiceType;
    district: string;
    state: string;
    preferredDate: string;
    problemDescription: string;
    phoneNumber: string;
    location: string;
    timeSlot: TimeSlot;
}
export interface Service {
    id: bigint;
    descriptionHindi: string;
    nameHindi: string;
    name: string;
    description: string;
    priceRange: string;
    category: string;
}
export type Result_1 = {
    __kind__: "ok";
    ok: Service;
} | {
    __kind__: "err";
    err: string;
};
export interface BookingRecord {
    id: bigint;
    customerName: string;
    status: BookingStatus;
    serviceType: ServiceType;
    district: string;
    state: string;
    preferredTimeSlot: TimeSlot;
    preferredDate: string;
    timestamp: Time;
    problemDescription: string;
    phoneNumber: string;
    location: string;
}
export interface Settings {
    businessHours: string;
    businessName: string;
    businessAddress: string;
    whatsappNumber: string;
    contactPhone: string;
}
export type Result = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export interface ServiceInput {
    descriptionHindi: string;
    nameHindi: string;
    name: string;
    description: string;
    priceRange: string;
    category: string;
}
export interface UserProfile {
    name: string;
    email: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed",
    inProgress = "inProgress"
}
export enum ServiceType {
    geyserRepair = "geyserRepair",
    lcdLedTvRepair = "lcdLedTvRepair",
    washingMachineRepair = "washingMachineRepair",
    waterPurifier = "waterPurifier",
    microwaveRepair = "microwaveRepair",
    refrigeratorRepair = "refrigeratorRepair",
    acRepair = "acRepair"
}
export enum TimeSlot {
    afternoon_12_4 = "afternoon_12_4",
    morning_9_12 = "morning_9_12",
    evening_4_7 = "evening_4_7"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBooking(input: BookingInput): Promise<Result_2>;
    createService(input: ServiceInput): Promise<Result_1>;
    deleteService(id: bigint): Promise<Result>;
    getAllBookings(): Promise<Array<BookingRecord>>;
    getAllServices(): Promise<Array<Service>>;
    getBookingById(bookingId: bigint): Promise<BookingRecord | null>;
    getBookingsByDistrict(district: string): Promise<Array<BookingRecord>>;
    getBookingsByLocation(location: string): Promise<Array<BookingRecord>>;
    getBookingsByServiceType(serviceType: ServiceType): Promise<Array<BookingRecord>>;
    getBookingsByState(state: string): Promise<Array<BookingRecord>>;
    getBookingsByStatus(status: BookingStatus): Promise<Array<BookingRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDistrictsByState(state: string): Promise<Array<string>>;
    getServiceById(id: bigint): Promise<Service | null>;
    getServicesByCategory(category: string): Promise<Array<Service>>;
    getSettings(): Promise<Settings>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchBookingsByCustomerName(name: string): Promise<Array<BookingRecord>>;
    searchServicesByName(name: string): Promise<Array<Service>>;
    updateBookingStatus(bookingId: bigint, newStatus: BookingStatus): Promise<void>;
    updateSettings(newSettings: Settings): Promise<void>;
}
import type { BookingInput as _BookingInput, BookingRecord as _BookingRecord, BookingStatus as _BookingStatus, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Service as _Service, ServiceType as _ServiceType, Time as _Time, TimeSlot as _TimeSlot, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBooking(arg0: BookingInput): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_BookingInput_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_2_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_BookingInput_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_2_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createService(arg0: ServiceInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createService(arg0);
                return from_candid_Result_1_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createService(arg0);
            return from_candid_Result_1_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteService(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBookings(): Promise<Array<BookingRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return result;
        }
    }
    async getBookingById(arg0: bigint): Promise<BookingRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingById(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingById(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByDistrict(arg0: string): Promise<Array<BookingRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByDistrict(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByDistrict(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByLocation(arg0: string): Promise<Array<BookingRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByLocation(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByLocation(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByServiceType(arg0: ServiceType): Promise<Array<BookingRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByServiceType(to_candid_ServiceType_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByServiceType(to_candid_ServiceType_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByState(arg0: string): Promise<Array<BookingRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByState(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByState(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByStatus(arg0: BookingStatus): Promise<Array<BookingRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByStatus(to_candid_BookingStatus_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByStatus(to_candid_BookingStatus_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDistrictsByState(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDistrictsByState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDistrictsByState(arg0);
            return result;
        }
    }
    async getServiceById(arg0: bigint): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceById(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceById(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServicesByCategory(arg0: string): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServicesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServicesByCategory(arg0);
            return result;
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchBookingsByCustomerName(arg0: string): Promise<Array<BookingRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchBookingsByCustomerName(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchBookingsByCustomerName(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchServicesByName(arg0: string): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchServicesByName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchServicesByName(arg0);
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSettings(arg0: Settings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
}
function from_candid_BookingRecord_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingRecord): BookingRecord {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TimeSlot_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimeSlot): TimeSlot {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookingRecord]): BookingRecord | null {
    return value.length === 0 ? null : from_candid_BookingRecord_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Service | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: _BookingStatus;
    serviceType: _ServiceType;
    district: string;
    state: string;
    preferredTimeSlot: _TimeSlot;
    preferredDate: string;
    timestamp: _Time;
    problemDescription: string;
    phoneNumber: string;
    location: string;
}): {
    id: bigint;
    customerName: string;
    status: BookingStatus;
    serviceType: ServiceType;
    district: string;
    state: string;
    preferredTimeSlot: TimeSlot;
    preferredDate: string;
    timestamp: Time;
    problemDescription: string;
    phoneNumber: string;
    location: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_BookingStatus_n18(_uploadFile, _downloadFile, value.status),
        serviceType: from_candid_ServiceType_n20(_uploadFile, _downloadFile, value.serviceType),
        district: value.district,
        state: value.state,
        preferredTimeSlot: from_candid_TimeSlot_n22(_uploadFile, _downloadFile, value.preferredTimeSlot),
        preferredDate: value.preferredDate,
        timestamp: value.timestamp,
        problemDescription: value.problemDescription,
        phoneNumber: value.phoneNumber,
        location: value.location
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Service;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Service;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    inProgress: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "confirmed" in value ? BookingStatus.confirmed : "inProgress" in value ? BookingStatus.inProgress : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    geyserRepair: null;
} | {
    lcdLedTvRepair: null;
} | {
    washingMachineRepair: null;
} | {
    waterPurifier: null;
} | {
    microwaveRepair: null;
} | {
    refrigeratorRepair: null;
} | {
    acRepair: null;
}): ServiceType {
    return "geyserRepair" in value ? ServiceType.geyserRepair : "lcdLedTvRepair" in value ? ServiceType.lcdLedTvRepair : "washingMachineRepair" in value ? ServiceType.washingMachineRepair : "waterPurifier" in value ? ServiceType.waterPurifier : "microwaveRepair" in value ? ServiceType.microwaveRepair : "refrigeratorRepair" in value ? ServiceType.refrigeratorRepair : "acRepair" in value ? ServiceType.acRepair : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    afternoon_12_4: null;
} | {
    morning_9_12: null;
} | {
    evening_4_7: null;
}): TimeSlot {
    return "afternoon_12_4" in value ? TimeSlot.afternoon_12_4 : "morning_9_12" in value ? TimeSlot.morning_9_12 : "evening_4_7" in value ? TimeSlot.evening_4_7 : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingRecord>): Array<BookingRecord> {
    return value.map((x)=>from_candid_BookingRecord_n16(_uploadFile, _downloadFile, x));
}
function to_candid_BookingInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingInput): _BookingInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TimeSlot_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeSlot): _TimeSlot {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    serviceType: ServiceType;
    district: string;
    state: string;
    preferredDate: string;
    problemDescription: string;
    phoneNumber: string;
    location: string;
    timeSlot: TimeSlot;
}): {
    customerName: string;
    serviceType: _ServiceType;
    district: string;
    state: string;
    preferredDate: string;
    problemDescription: string;
    phoneNumber: string;
    location: string;
    timeSlot: _TimeSlot;
} {
    return {
        customerName: value.customerName,
        serviceType: to_candid_ServiceType_n5(_uploadFile, _downloadFile, value.serviceType),
        district: value.district,
        state: value.state,
        preferredDate: value.preferredDate,
        problemDescription: value.problemDescription,
        phoneNumber: value.phoneNumber,
        location: value.location,
        timeSlot: to_candid_TimeSlot_n7(_uploadFile, _downloadFile, value.timeSlot)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    inProgress: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value == BookingStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    geyserRepair: null;
} | {
    lcdLedTvRepair: null;
} | {
    washingMachineRepair: null;
} | {
    waterPurifier: null;
} | {
    microwaveRepair: null;
} | {
    refrigeratorRepair: null;
} | {
    acRepair: null;
} {
    return value == ServiceType.geyserRepair ? {
        geyserRepair: null
    } : value == ServiceType.lcdLedTvRepair ? {
        lcdLedTvRepair: null
    } : value == ServiceType.washingMachineRepair ? {
        washingMachineRepair: null
    } : value == ServiceType.waterPurifier ? {
        waterPurifier: null
    } : value == ServiceType.microwaveRepair ? {
        microwaveRepair: null
    } : value == ServiceType.refrigeratorRepair ? {
        refrigeratorRepair: null
    } : value == ServiceType.acRepair ? {
        acRepair: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeSlot): {
    afternoon_12_4: null;
} | {
    morning_9_12: null;
} | {
    evening_4_7: null;
} {
    return value == TimeSlot.afternoon_12_4 ? {
        afternoon_12_4: null
    } : value == TimeSlot.morning_9_12 ? {
        morning_9_12: null
    } : value == TimeSlot.evening_4_7 ? {
        evening_4_7: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
