/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingInput {
  'customerName' : string,
  'serviceType' : ServiceType,
  'district' : string,
  'state' : string,
  'preferredDate' : string,
  'problemDescription' : string,
  'phoneNumber' : string,
  'location' : string,
  'timeSlot' : TimeSlot,
}
export interface BookingRecord {
  'id' : bigint,
  'customerName' : string,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'district' : string,
  'state' : string,
  'preferredTimeSlot' : TimeSlot,
  'preferredDate' : string,
  'timestamp' : Time,
  'problemDescription' : string,
  'phoneNumber' : string,
  'location' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'inProgress' : null };
export type Result = { 'ok' : boolean } |
  { 'err' : string };
export type Result_1 = { 'ok' : Service } |
  { 'err' : string };
export interface Service {
  'id' : bigint,
  'descriptionHindi' : string,
  'nameHindi' : string,
  'name' : string,
  'description' : string,
  'priceRange' : string,
  'category' : string,
}
export interface ServiceInput {
  'descriptionHindi' : string,
  'nameHindi' : string,
  'name' : string,
  'description' : string,
  'priceRange' : string,
  'category' : string,
}
export type ServiceType = { 'geyserRepair' : null } |
  { 'lcdLedTvRepair' : null } |
  { 'washingMachineRepair' : null } |
  { 'waterPurifier' : null } |
  { 'microwaveRepair' : null } |
  { 'refrigeratorRepair' : null } |
  { 'acRepair' : null };
export interface Settings {
  'businessHours' : string,
  'businessName' : string,
  'businessAddress' : string,
  'whatsappNumber' : string,
  'contactPhone' : string,
}
export type Time = bigint;
export type TimeSlot = { 'afternoon_12_4' : null } |
  { 'morning_9_12' : null } |
  { 'evening_4_7' : null };
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<[BookingInput], bigint>,
  'createService' : ActorMethod<[ServiceInput], Result_1>,
  'deleteService' : ActorMethod<[bigint], Result>,
  'getAllBookings' : ActorMethod<[], Array<BookingRecord>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getBookingById' : ActorMethod<[bigint], [] | [BookingRecord]>,
  'getBookingsByDistrict' : ActorMethod<[string], Array<BookingRecord>>,
  'getBookingsByLocation' : ActorMethod<[string], Array<BookingRecord>>,
  'getBookingsByServiceType' : ActorMethod<[ServiceType], Array<BookingRecord>>,
  'getBookingsByState' : ActorMethod<[string], Array<BookingRecord>>,
  'getBookingsByStatus' : ActorMethod<[BookingStatus], Array<BookingRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDistrictsByState' : ActorMethod<[string], Array<string>>,
  'getServiceById' : ActorMethod<[bigint], [] | [Service]>,
  'getServicesByCategory' : ActorMethod<[string], Array<Service>>,
  'getSettings' : ActorMethod<[], Settings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchBookingsByCustomerName' : ActorMethod<[string], Array<BookingRecord>>,
  'searchServicesByName' : ActorMethod<[string], Array<Service>>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateSettings' : ActorMethod<[Settings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];