/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'geyserRepair' : IDL.Null,
  'lcdLedTvRepair' : IDL.Null,
  'washingMachineRepair' : IDL.Null,
  'waterPurifier' : IDL.Null,
  'microwaveRepair' : IDL.Null,
  'refrigeratorRepair' : IDL.Null,
  'acRepair' : IDL.Null,
});
export const TimeSlot = IDL.Variant({
  'afternoon_12_4' : IDL.Null,
  'morning_9_12' : IDL.Null,
  'evening_4_7' : IDL.Null,
});
export const BookingInput = IDL.Record({
  'customerName' : IDL.Text,
  'serviceType' : ServiceType,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'preferredDate' : IDL.Text,
  'problemDescription' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'location' : IDL.Text,
  'timeSlot' : TimeSlot,
});
export const ServiceInput = IDL.Record({
  'descriptionHindi' : IDL.Text,
  'nameHindi' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'priceRange' : IDL.Text,
  'category' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'descriptionHindi' : IDL.Text,
  'nameHindi' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'priceRange' : IDL.Text,
  'category' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : Service, 'err' : IDL.Text });
export const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Time = IDL.Int;
export const BookingRecord = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'preferredTimeSlot' : TimeSlot,
  'preferredDate' : IDL.Text,
  'timestamp' : Time,
  'problemDescription' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Settings = IDL.Record({
  'businessHours' : IDL.Text,
  'businessName' : IDL.Text,
  'businessAddress' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'contactPhone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func([BookingInput], [IDL.Nat], []),
  'createService' : IDL.Func([ServiceInput], [Result_1], []),
  'deleteService' : IDL.Func([IDL.Nat], [Result], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(BookingRecord)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getBookingById' : IDL.Func([IDL.Nat], [IDL.Opt(BookingRecord)], ['query']),
  'getBookingsByDistrict' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BookingRecord)],
      ['query'],
    ),
  'getBookingsByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BookingRecord)],
      ['query'],
    ),
  'getBookingsByServiceType' : IDL.Func(
      [ServiceType],
      [IDL.Vec(BookingRecord)],
      ['query'],
    ),
  'getBookingsByState' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BookingRecord)],
      ['query'],
    ),
  'getBookingsByStatus' : IDL.Func(
      [BookingStatus],
      [IDL.Vec(BookingRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDistrictsByState' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getServiceById' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
  'getServicesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Service)], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchBookingsByCustomerName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BookingRecord)],
      ['query'],
    ),
  'searchServicesByName' : IDL.Func([IDL.Text], [IDL.Vec(Service)], ['query']),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateSettings' : IDL.Func([Settings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'geyserRepair' : IDL.Null,
    'lcdLedTvRepair' : IDL.Null,
    'washingMachineRepair' : IDL.Null,
    'waterPurifier' : IDL.Null,
    'microwaveRepair' : IDL.Null,
    'refrigeratorRepair' : IDL.Null,
    'acRepair' : IDL.Null,
  });
  const TimeSlot = IDL.Variant({
    'afternoon_12_4' : IDL.Null,
    'morning_9_12' : IDL.Null,
    'evening_4_7' : IDL.Null,
  });
  const BookingInput = IDL.Record({
    'customerName' : IDL.Text,
    'serviceType' : ServiceType,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'preferredDate' : IDL.Text,
    'problemDescription' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'location' : IDL.Text,
    'timeSlot' : TimeSlot,
  });
  const ServiceInput = IDL.Record({
    'descriptionHindi' : IDL.Text,
    'nameHindi' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'priceRange' : IDL.Text,
    'category' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'descriptionHindi' : IDL.Text,
    'nameHindi' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'priceRange' : IDL.Text,
    'category' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : Service, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Time = IDL.Int;
  const BookingRecord = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'serviceType' : ServiceType,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'preferredTimeSlot' : TimeSlot,
    'preferredDate' : IDL.Text,
    'timestamp' : Time,
    'problemDescription' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Settings = IDL.Record({
    'businessHours' : IDL.Text,
    'businessName' : IDL.Text,
    'businessAddress' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func([BookingInput], [IDL.Nat], []),
    'createService' : IDL.Func([ServiceInput], [Result_1], []),
    'deleteService' : IDL.Func([IDL.Nat], [Result], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(BookingRecord)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getBookingById' : IDL.Func([IDL.Nat], [IDL.Opt(BookingRecord)], ['query']),
    'getBookingsByDistrict' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BookingRecord)],
        ['query'],
      ),
    'getBookingsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BookingRecord)],
        ['query'],
      ),
    'getBookingsByServiceType' : IDL.Func(
        [ServiceType],
        [IDL.Vec(BookingRecord)],
        ['query'],
      ),
    'getBookingsByState' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BookingRecord)],
        ['query'],
      ),
    'getBookingsByStatus' : IDL.Func(
        [BookingStatus],
        [IDL.Vec(BookingRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDistrictsByState' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getServiceById' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
    'getServicesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchBookingsByCustomerName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BookingRecord)],
        ['query'],
      ),
    'searchServicesByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateSettings' : IDL.Func([Settings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };